### ISSUE TITLE
Enable dynamic arrays

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#1011] opened 2023-03-20 17:28 UTC
### Problem

Dynamic arrays are implemented in PR #886 but they are disabled within the PR because of verification failing the integration test.

### Proposed solution

We should fix the issue and enable dynamic arrays:
- allows to write arrays with field index type in the fronted
- enable the integration test in 6_array

**Comment by Globallager** [comment] 2023-03-24 06:26
Is this a duplicate of https://github.com/noir-lang/noir/issues/507?

**Comment by guipublic** [comment] 2023-03-24 08:50
No, dynamic arrays are now implemented but they are not activated yet.
The implementation change the index from `comptime FieldElement` to `FieldElement`, so the issue #507 remains valid.

**Comment by colinnielsen** [comment] 2023-04-19 03:42
@guipublic are dynamic arrays enabled in nargo 0.3.2?

**Comment by guipublic** [comment] 2023-04-19 09:14
> @guipublic are dynamic arrays enabled in nargo 0.3.2?

No, the test case does not verify. This should not happen since noir proofs should be valid. We have other cases with the same issue (some are very simple) so we suspect a problem on the backend. Since we are going to switch to a new backend very soon, we are just waiting for the new backend.

**Closed** 2023-05-03 10:28 UTC
Labels: enhancement
