### ISSUE TITLE
Test named `sha2_byte` crashes during compliation

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1629] opened 2023-06-09 17:38 UTC
### Aim

Test named `sha2_byte` should compile

### Expected Behavior

^

### Bug

It appears to hang during the cfg flatten pass.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment] 2023-06-10 05:15
Duplicate of #1259

**Comment by joss-aztec** [comment] 2023-06-14 15:38
Also affects test named `sha2_blocks`

**Comment by ludamad** [comment] 2023-06-21 19:11
This turns out to be related to https://github.com/noir-lang/noir/issues/1756. This can be seen by removing the top half of the called sha function:

```

// SHA-256 hash function
fn digest<N>(msg: [u8; N]) -> [u8; 32] {
    let mut msg_block: [u8; 64] = [0; 64];
    let mut h: [u32; 8] = [1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225]; // Intermediate hash, starting with the canonical initial value
    let mut c: [u32; 8] = [0; 8]; // Compression of current message block as sequence of u32
    let mut out_h: [u8; 32] = [0; 32]; // Digest as sequence of bytes
    let mut i = 0; // Message byte pointer

    for k in 0 .. msg.len() {
        // Populate msg_block
        msg_block[i] = msg[k];
        i = i + 1;
        if i == 64 { // Enough to hash block
            c = sha_c(msg_u8_to_u32(msg_block), h);
            for j in 0..8 {
                h[j] = c[j] + h[j];
            }
            
            i = 0;
        }
    }

    // Pad the rest such that we have a [u32; 2] block at the end representing the length
    // of the message, and a block of 1 0 ... 0 following the message (i.e. [1 << 7, 0, ..., 0]).
    msg_block[i] = 1 << 7;
    i = i + 1;


    out_h
}
```
Which gets the 
```
Message:  internal error: entered unreachable code: Expected all allocate instructions to be removed before acir_gen
Location: crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs:258
```
error

**Comment by jfecher** [comment] 2023-06-22 16:36
The original error is gone now but `sha2_byte` now crashes with:
```
The application panicked (crashed).
Message:  Vector::index_mut: index out of bounds
Location: /Users/.../.cargo/registry/src/github.com-1ecc6299db9ec823/im-15.1.0/./src/vector/mod.rs:838
```

**Closed** 2023-06-22 21:27 UTC
Labels: bug, refactor, ssa, e2e
