### ISSUE TITLE
Compilation: The application panicked (crashed).

### ISSUE THREAD

**Issue by bajpai244** [noir-lang/noir#1146] opened 2023-04-13 06:20 UTC
### Aim

The aim was to compile the circuit { it is the circuit that nargo new creates by default }.

### Expected behavior

```shell
nargo compile main
```

The above should compile.

### Bug

Gives the following error:

```shell
SRS is located at : "/Users/harshbajpai/noir_cache/ignition/transcript00.dat"
The application panicked (crashed).
Message:  range end index 322560156 out of range for slice of length 257440
Location: /Users/runner/.cargo/git/checkouts/aztec_backend-a697fb631cbad807/2cb523d/common/src/crs.rs:37
```

<img width="988" alt="image" src="https://user-images.githubusercontent.com/41180869/231670553-e81b0437-47f2-4291-8b87-fde96238f78c.png">

### To reproduce

1. noir new circuit
2. noir compile main

### Installation method

Binary

### @noir-lang/noir_wasm version

nargo 0.3.2 (git version hash: 29b1f7df4d563849a62e64c533cb62932188135b, is dirty: false

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by Globallager** [comment] 2023-04-14 06:20
Closing as it seems like a duplicate of https://github.com/noir-lang/noir/issues/615.

Do reopen this issue if the redownloading `transcript00.dat` workaround as suggested in that issue [here](https://github.com/noir-lang/noir/issues/615#issuecomment-1458880678) isn't working for you.

**Closed by Globallager** 2023-04-14 06:20 UTC
Labels: bug
