### ISSUE TITLE
nargo test passes or fails arbitrarily with no changes to the code

### ISSUE THREAD

**Issue by harshnambiar** [noir-lang/noir#1986] opened 2023-07-20 12:56 UTC
### Aim

While adding tests to [this](https://github.com/resurgencelabs/fraction) repository, I ran nargo test twice. Once it failed, and once it didn't. I had made no changes to the code between the nargo test commands. 

### Expected Behavior

The tests should ideally both pass.

### Bug

However, only once it did. When I kept running nargo test again and again, the test always subsequently passed. However, if someone runs it just once, they might wrongly interpret that a test is failing.

### To Reproduce

1. clone the repository mentioned above
2. cd fraction
3. nargo test

### Installation Method

None

### Nargo Version

0.7.1

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment] 2023-07-20 20:03
I've confirmed that this does not occur with `--experimental-ssa` (the tests always pass with it). So it seems there is some nondeterministic part of the old SSA code. Because it is only occurring in the old ssa code that we'll be removing anyway, I'm going to leave this issue until the experimental ssa is switched on in Noir by default. Until then, you can use the `--experimental-ssa` flag as a workaround.

**Comment by TomAFrench** [comment] 2023-07-27 05:22
Closing as the legacy SSA code is now no longer supported.

**Comment by harshnambiar** [comment] 2023-08-11 07:06
So I'm on 0.9.0 and the same library tests are still causing this problem. Here is the terminal output for 2 consecutive runs with no changes inbetween:

`ritik@HP-EliteBook-8460w:~/hello_aztec/fraction$ nargo test
Running 18 test functions...
Testing test_cube...
ok
Testing test_diff...
failed
Testing test_sum...
ok
Testing test_integer...
ok
Testing test_square...
ok
Testing test_ceiling...
ok
Testing test_globals...
ok
Testing test_ceiling2...
ok
Testing test_compare...
ok
Testing test_floor2...
ok
Testing test_reduce...
ok
Testing test_sum_negative...
failed
Testing test_not_integer...
ok
Testing test_floor...
ok
Testing test_zero_neutrality...
ok
Testing test_inv...
ok
Testing test_mul...
ok
Testing test_div...
ok
Error: 2 tests failed

Location:
    crates/nargo_cli/src/cli/mod.rs:74:5
ritik@HP-EliteBook-8460w:~/hello_aztec/fraction$ nargo test
Running 18 test functions...
Testing test_floor2...
ok
Testing test_diff...
ok
Testing test_floor...
ok
Testing test_inv...
ok
Testing test_integer...
ok
Testing test_not_integer...
ok
Testing test_ceiling...
ok
Testing test_cube...
ok
Testing test_zero_neutrality...
ok
Testing test_sum...
ok
Testing test_ceiling2...
ok
Testing test_div...
ok
Testing test_mul...
ok
Testing test_sum_negative...
ok
Testing test_compare...
ok
Testing test_reduce...
ok
Testing test_square...
ok
Testing test_globals...
ok
All tests `passed`
`

Is it ok to reopen this?

**Comment by TomAFrench** [comment] 2023-08-11 07:18
Yep, if you're still experiencing this then we should have an issue open for it.

**Comment by TomAFrench** [comment] 2023-08-11 07:26
I can reproduce on 0.9.0 but not on the nightly release. Can you check if it's fixed for you on that?

**Comment by jfecher** [comment] 2023-08-11 16:10
`0.10.0` will be the first release with the legacy SSA code removed (and the old `--experimental-ssa` flag made the default), so it is expected that this is still failing on 0.9.0.

**Closed** 2023-08-11 16:19 UTC
Labels: bug, reviewed-Q3-2023, P-HIGH, E-LOW
