### ISSUE TITLE
ICE: unreachable code

### ISSUE THREAD

**Issue by nventuro** [noir-lang/noir#4497] opened 2024-03-06 21:46 UTC
### Aim

I run into an ICE while performing routine development.

### Expected Behavior

I expected to not run into an ICE?

### Bug

I get the following error message:

```
The application panicked (crashed).
Message:  internal error: entered unreachable code: Expected all allocate instructions to be removed before acir_gen
Location: compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs:498
```

I produced a relatively minimal example, in which calling a trivial `unconstrained` function triggers the ICE, and calling a copy of that function that is constrained does not.

### To Reproduce

The example can be found in [this commit](https://github.com/AztecProtocol/aztec-packages/commit/a3b17b9472677e967651886f1fd2cff4d9f76ef8). 

1. `git checkout a3b17b9472677e967651886f1fd2cff4d9f76ef8`
2. `cd noir-projects/noir-contracts/`
3. `nargo compile --package ice_contract --silence-warnings`
4. cry

If the call to `view_notes` is commented out and the call to `view_notes_constrained` is uncommented, there's no compilation error. Both functions [are identical](https://github.com/AztecProtocol/aztec-packages/blob/a3b17b9472677e967651886f1fd2cff4d9f76ef8/noir-projects/aztec-nr/aztec/src/state_vars/private_set.nr#L84) except for the `unconstrained` modifier.

### Project Impact

Blocker

### Workaround

None

### Installation Method

Compiled from source

### Nargo Version

 nargo version = 0.24.0 noirc version = 0.24.0+edaef211ea08832b1aaabcfc8b3f2419c3a2184c (git version hash: edaef211ea08832b1aaabcfc8b3f2419c3a2184c, is dirty: false)

### Would you like to submit a PR for this Issue?

None

**Comment by Savio-Sou** [comment] 2024-03-08 16:41
@nventuro would you be able to come up with a minimal reproduction that relies less on Aztec.nr? That'd be super helpful to ease our further debugging.

**Comment by nventuro** [comment] 2024-03-08 20:48
I was unable - I tried replicating this by creating a second crate and calling a function declared there, but doing so I ended up triggering a different ICE: see https://github.com/noir-lang/noir/issues/4517. 

The original example shown here does not rely very much on aztec-nr however, there's no library code called.

**Comment by Savio-Sou** [comment] 2024-03-11 17:11
Ah sorry I meant Aztec macros instead of Aztec.nr.

As there could be the possibility that the bug lies within the macros, it'd be great to get a macro-less reproduction to better identify where the problem lies.

**Comment by TomAFrench** [comment] 2024-04-20 23:12
Closing this as this seems to be more of an aztec_macros issue than Noir.

**Closed by TomAFrench** 2024-04-20 23:12 UTC
Labels: bug
