### ISSUE TITLE
[Nargo] nargo prove crashes

### ISSUE THREAD

**Issue by literallymarvellous** [noir-lang/noir#1021] opened 2023-03-21 17:55 UTC
### Aim

Tried creating a proof based on tutorial from BattleZips video 03

### Expected behavior

A proof folder containing a proof file to be created.

### Bug

SRS is located at : "/Users/marvellous/noir_cache/ignition/transcript00.dat"

The application panicked (crashed).

Message:  range end index 322560156 out of range for slice of length 298697158

Location: /Users/runner/.cargo/git/checkouts/aztec_backend-a697fb631cbad807/2cb523d/common/src/crs.rs:37

### To reproduce

1. Create a project with ```nargo new```
2. Add a prover.toml with x = "3" and y = "4", verifier.toml with y="4" also tried "0x0000000000000000000000000000000000000000000000000000000000000004"
3. Run ```cargo check```
4. Run ```nargo prove p```

### Installation method

Binary

### Nargo version

nargo 0.3.2 (git version hash: 4f3208dbad8ca69eec80674ddb1cb26593cd5d63, is dirty: false)

**Comment by TomAFrench** [comment] 2023-03-21 18:52
This looks like a duplicate of https://github.com/noir-lang/noir/issues/615. Can you try the steps in that issue to see if that fixes the issue?

**Comment by literallymarvellous** [comment] 2023-03-21 19:09
Works now, thanks.

**Closed** 2023-03-21 19:22 UTC
Labels: bug
