### ISSUE TITLE
Compiler panic when From is used

### ISSUE THREAD

**Issue by LogvinovLeon** [noir-lang/noir#4901] opened 2024-04-24 13:39 UTC
### Aim

I want to be able to use From/Into traits

### Expected Behavior

They work

### Bug

The application panicked (crashed).
Message:  ICE: missing trait impl - should be caught during type checking
Location: compiler/noirc_frontend/src/monomorphization/mod.rs:994

### To Reproduce

```rs
use dep::std::unsafe::zeroed;

pub fn resize<TItem, NEW_LEN, OLD_LEN>(src: [TItem; OLD_LEN]) -> [TItem; NEW_LEN] {
    assert(NEW_LEN >= OLD_LEN, "New length must be greater than or equal to old length");
    let mut dest = [zeroed(); NEW_LEN];
    for i in 0..OLD_LEN {
        dest[i] = src[i];
    }
    dest
}

struct Fragment<MAX_DATA_LEN> {
    data: [u8; MAX_DATA_LEN]
}

impl<DATA_LEN, MAX_DATA_LEN>  From<[u8; DATA_LEN]> for Fragment<MAX_DATA_LEN> {
    fn from(data: [u8; DATA_LEN]) -> Fragment<MAX_DATA_LEN> {
        Fragment { data: resize(data) }
    }
}


global MAX_PREFIXED_KEY_NIBBLE_LEN = 6;
global some_key: [u8; 2] = [0xab, 0xcd];
global some_key_fragment: Fragment<MAX_PREFIXED_KEY_NIBBLE_LEN> = From::from(some_key);

fn main() {
    println(some_key_fragment);
}
```

### Project Impact

Nice-to-have

### Impact Context

I can't use From/Into and am forced to write converter functions instead which is uglier

### Workaround

Yes

### Workaround Description

Convert using a function

### Installation Method

Binary (`noirup` default)

### Nargo Version

0.26.0

### Would you like to submit a PR for this Issue?

None

**Comment by asterite** [comment] 2024-07-29 16:23
Fixed by #5602

Duplicate of #5602 and #5017

Please reopen if the code above still crashes on master.

**Closed by asterite** 2024-07-29 16:23 UTC
Labels: bug
