### ISSUE TITLE
RSA lib test succeeds, but doesn't compile with nargo v0.370+

### ISSUE THREAD

**Issue by iAmMichaelConnor** [noir-lang/noir#6462] opened 2024-11-06 11:29 UTC
Checkout this PR:

https://github.com/noir-lang/noir_rsa/pull/29

`noirup --version v0.37.0`

`cd example`

`nargo test` <-- this succeeds.

`nargo compile` <-- this fails with:

![Image](https://github.com/user-attachments/assets/28b1ea78-0885-4108-98aa-ef5b30dd1d76)

**Comment by TomAFrench** [comment] 2024-11-06 11:43
Duplicate of https://github.com/noir-lang/noir/issues/6451

**Closed by TomAFrench** 2024-11-06 11:43 UTC
Labels: bug

**Comment by iAmMichaelConnor** [comment] 2024-11-06 11:44
Oh, whoops! I did search, but the title of the other is too technical for me :D
