### ISSUE TITLE
Runtime memory corruption when using std::Option in a trait

### ISSUE THREAD

**Issue by grasshopper47** [noir-lang/noir#3491] opened 2023-11-14 18:36 UTC
### Aim

To be possible to provide a (functional) default implementation in a `trait` defining a method which returns an `Option` struct.

### Expected Behavior

The code in the attached file should work as written.

### Bug

While a default implementation for a trait compiles, and simple cases seem to work, there is a problem when dealing with more complex structs, such as those shown in the attached source file, which leads to memory corruption. To elucidate this (quite weird) runtime behavior I've prepared a file demonstrating 4 ways to re-create the issue.

### To Reproduce

1. Kindly download this 356-line [Google Drive shared file](https://drive.google.com/file/d/1I2GObAvajW6FWAoQYmNzveQL9170UQRR) into a simple `Noir` project, running `Nargo` **0.19.2** and call `nargo test --show_output`.
2. View the [video explanation](https://drive.google.com/file/d/1Z-DZawSdGmBnXBNqWJrHAzA2tA_ET3v5) for context on interpreting the source code in the shared file. The first 4:30 minutes cover the code, the remaining 8 minutes details the memory corruption behavior.

### Installation Method

None

### Nargo Version

noirc version = 0.19.2+d7f919dcc001080ed24616ebbc37426ef7ac7638

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment] 2023-11-20 22:30
Hi,

Thanks for the project report.

> Kindly download this 356-line [Google Drive shared file](https://drive.google.com/file/d/1I2GObAvajW6FWAoQYmNzveQL9170UQRR) into a simple Noir project

Are you able to make a github project instead or a github gist?

**Comment by grasshopper47** [comment] 2023-11-21 21:06
> Hi,
> 
> Thanks for the bug report.
> 
> > Kindly download this 356-line [Google Drive shared file](https://drive.google.com/file/d/1I2GObAvajW6FWAoQYmNzveQL9170UQRR) into a simple Noir project
> 
> Are you able to make a github project instead or a github gist?

https://github.com/grasshopper47/nargo-option-trait-memory-corruption

**Comment by jfecher** [comment] 2024-01-17 18:45
Currently unable to test this issue anymore since nested slices are now disallowed

**Comment by TomAFrench** [comment] 2024-12-09 16:56
I'm going to tentatively close this issue as the code in the reproduction is now disallowed. If this reoccurs, please reopen with a new reproduction.

**Closed by TomAFrench** 2024-12-09 16:56 UTC
Labels: bug
