### ISSUE TITLE
Compiler panics when trying to create a mutable reference of an undefined variable

### ISSUE THREAD

**Issue by iAmMichaelConnor** [noir-lang/noir#1985] opened 2023-07-20 12:36 UTC
This isn't blocking anything, so not a high priority. It's just something I stumbled upon.

```
fn my_mutating_fn(a: &mut Field) {
    a += 10;
}

fn main(mut a: Field) -> pub Field {
    my_mutating_fn(&mut a);
    a
}
```

<img width="770" alt="image" src="https://github.com/noir-lang/noir/assets/42943676/26658809-8cc1-4123-a949-73ee6a212812">

I'd have expected `+` to work here.

Compiled using the latest `master`, from source.

**Comment by f01dab1e** [comment] 2023-07-20 12:52
looks like you forgot to deref, but still get error in noir

```rust
fn my_mutating_fn(a: &mut Field) {
    *a += 10;
}

fn main(mut x: Field) -> pub Field {
    my_mutating_fn(&mut a);
    a
}
```

```bash
$ nargo execute --show-ssa --experimental-ssa
The application panicked (crashed).
Message:  index out of bounds: the len is 1254 but the index is 18446744073709551615
Location: crates/noirc_frontend/src/node_interner.rs:482

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

**Comment by iAmMichaelConnor** [comment] 2023-07-20 12:54
Doh! Good catch.
Your error is even better!

**Comment by jfecher** [comment] 2023-07-20 14:43
Thanks for the crash report, I've fixed it locally and will have a PR up soon. The issue is that in `main` you're using `a` which was not declared and the mutable reference code did not have a check for this case. Since it needs to check a variable's definition to see if it is mutable and `a` had no definition. Here's the new error messages with the fix:
```
error: cannot find `a` in this scope 
  ┌─ /.../src/main.nr:8:25
  │
8 │     my_mutating_fn(&mut a);
  │                         - not found in this scope

error: cannot find `a` in this scope 
  ┌─ /.../src/main.nr:9:5
  │
9 │     a
  │     - not found in this scope

warning: unused variable x
  ┌─ /.../src/main.nr:7:13
  │
7 │ fn main(mut x: Field) -> pub Field {
  │             - unused variable 
```

**Comment by jfecher** [comment] 2023-07-20 14:57
Looking at the original code again, it uses `a` everywhere and doesn't have the `x` parameter. So it was an uncaught mistake while copying that lead to catching a compiler bug.

@iAmMichaelConnor I would expect your code to work then with only adding the one dereference. Note that you need this dereference because, like in rust, references are separate from their element types. So you cannot add together a `&mut Field` and a `Field`. You also cannot assign to a `&mut Field` directly, oddly enough. You have to dereference it to signal that you're storing the Field in that reference, rather than mutating that reference to be a different reference.

**Closed** 2023-07-20 16:25 UTC
Labels: bug
