### ISSUE TITLE
`nargo fmt` incorrectly formats and breaks imports

### ISSUE THREAD

**Issue by benesjan** [noir-lang/noir#5304] opened 2024-06-21 09:00 UTC
### Aim

I tried to format noir-protocol-circuits.

### Expected Behavior

It formats it instead of breaking it.

### Bug

See the change in the screenshot

<img width="1044" alt="image" src="https://github.com/noir-lang/noir/assets/13470840/e8643e04-1e3b-4baf-875c-68262219d205">

### To Reproduce

1.
2.
3.
4.

### Project Impact

Nice-to-have

### Workaround

None

### Installation Method

None

### Nargo Version

nargo version = 0.30.0 noirc version = 0.30.0+109624f127dc8da6d9d963b3af9250237be0d4e4 (git version hash: 109624f127dc8da6d9d963b3af9250237be0d4e4, is dirty: false)

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment] 2024-06-21 11:01
Duplicate of https://github.com/noir-lang/noir/issues/5299

**Closed by TomAFrench** 2024-06-21 11:01 UTC
Labels: bug
