### ISSUE TITLE
ABI crashing with `called Option::unwrap() on a None value`

### ISSUE THREAD

**Issue by rahul-kothari** [noir-lang/noir#1170] opened 2023-04-18 11:16 UTC
### Aim

1. Better error message
2. Location is quite useful to an end program
3. Find the source of the bug (looking the noir-lang code, I suspect it is happening when it tries to decode a field value).

### Expected behavior

It to work

### Bug

```
> nargo prove p                 
                                        
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: crates/noirc_abi/src/lib.rs:354
```

## Code

```
struct BaseOrMergeRollupPublicInputs {
    rollup_type: u1,
    rollup_subtree_height: Field,
}

struct PreviousRollupData {
    base_or_merge_rollup_public_inputs: BaseOrMergeRollupPublicInputs
}

struct MergeRollupInputs {
    previous_rollup_data_0: PreviousRollupData,
}

fn main(merge_rollup_inputs: pub MergeRollupInputs) -> pub BaseOrMergeRollupPublicInputs {
    BaseOrMergeRollupPublicInputs {
        rollup_type: merge_rollup_inputs.previous_rollup_data_0.base_or_merge_rollup_public_inputs.rollup_type,
        rollup_subtree_height: merge_rollup_inputs.previous_rollup_data_0.base_or_merge_rollup_public_inputs.rollup_subtree_height,
    }
}
```

```
nargo check
nargo prove p
```

**Note: If I remove `rollup_type: u1` field then it magically works??**

### Installation method

Compiled from source

### Nargo version

nargo 0.3.2 (git version hash: 29b1f7df4d563849a62e64c533cb62932188135b, is dirty: false)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by TomAFrench** [comment] 2023-04-18 11:31
I think this may be a duplicate of https://github.com/noir-lang/noir/issues/942

**Comment by rahul-kothari** [comment] 2023-04-18 11:52
Yup agree!Am 18/04/2023 um 12:31 schrieb Tom French ***@***.***>:﻿
I think this may be a duplicate of #942

**Comment by TomAFrench** [comment] 2023-04-18 17:09
@rahul-kothari I can prove against this circuit on nargo 0.4.0. Can you check that this release works for you and reopen if you still run into this?

**Closed by TomAFrench** 2023-04-18 17:09 UTC
Labels: bug
