### ISSUE TITLE
Application panicked with `range start index 18446744072079599120 out of range for slice of length 4208525312` while running `nargo prove`

### ISSUE THREAD

**Issue by richardliang** [noir-lang/noir#2409] opened 2023-08-22 21:16 UTC
### Aim

Generating a proof for a email DKIM verification circuit for a 1024 bit RSA (goal is to ultimately generate one for 2048 bit which is double the size). The circuit uses RSA, SHA256 from the backend, and BigInt

### Expected Behavior

Proof should generate. Tests work for the same exact inputs for the circuit

### Bug

Got the following error:

```
The application panicked (crashed).
Message:  range start index 18446744072079599120 out of range for slice of length 4208525312
Location: /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/acvm-backend-barretenberg-0.10.0/src/lib.rs:456
```

Nargo info generated the following:
```
+---------+------------------------+--------------+----------------------+
| Package | Language               | ACIR Opcodes | Backend Circuit Size |
+---------+------------------------+--------------+----------------------+
| dkim    | PLONKCSat { width: 3 } | 1065057      | 2311183              |
+---------+------------------------+--------------+----------------------+
```

### To Reproduce

1. Clone repo https://github.com/SetProtocol/noir-rsa
2. cd `examples/dkim`
3. Run `nargo compile` and then `nargo prove` will give you the error
4. Running `nargo test` will succeed

### Installation Method

None

### Nargo Version

nargo 0.10.1 (git version hash: ba8ffd84c19b3516334c126bc2f25c725985baa3, is dirty: false)

### Would you like to submit a PR for this Issue?

Maybe

**Comment by jfecher** [comment] 2023-08-24 14:49
Can you minimize the code at all? I'm having trouble reproducing since `nargo compile` is taking more than 1 hour for me locally on this code.

**Comment by richardliang** [comment] 2023-08-24 15:21
I can reduce the BigUint56 limb size. `nargo compile` only took ~30s to run for me using this version `nargo 0.10.1 (git version hash: ba8ffd84c19b3516334c126bc2f25c725985baa3, is dirty: false)`

**Comment by richardliang** [comment] 2023-08-24 16:08
I've pushed up a new branch with a 19 limb BigUint56 (vs 37 limbs in the main branch) https://github.com/SetProtocol/noir-rsa/tree/richard/dkim-512

`nargo compile` takes <10s for me. However, `nargo prove` is now giving this error:
```
bad alloc of size: 33554464
Error: Trying to call acir_proofs_init_proving_key resulted in an error

Caused by:
   0: RuntimeError: unreachable
   1: unreachable

Location:
    crates/nargo_cli/src/cli/mod.rs:79:5
```

```
+---------+------------------------+--------------+----------------------+
| Package | Language               | ACIR Opcodes | Backend Circuit Size |
+---------+------------------------+--------------+----------------------+
| dkim    | PLONKCSat { width: 3 } | 301128       | 659381               |
+---------+------------------------+--------------+----------------------+
```

**Comment by kevaundray** [comment] 2023-09-15 09:54
The proving system has changed quite a lot since this and all proving is delegated to the bb binary. Closing this and we can re-open if the problem comes up again.

**Closed by kevaundray** 2023-09-15 09:54 UTC
Labels: bug, P-HIGH
