### ISSUE TITLE
Support `impl Trait` in a parameter position

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#4540] opened 2024-03-12 20:42 UTC
### Problem

Noir already has limited support for `impl Trait` in a return type position. It should also support `impl Trait` in a parameter position for consistency.

### Happy Case

`impl Trait` in a parameter position is added.

This is just sugar for a trait constraint on a generic parameter:
```rust
fn foo(x: impl Bar) {}

// same as
fn foo<T>(x: T) where T: Bar {}
```

### Project Impact

None

### Workaround

None

### Would you like to submit a PR for this Issue?

None

**Comment by michaeljklein** [comment] 2024-03-20 21:03
Duplicate of https://github.com/noir-lang/noir/issues/3771

See there for implementation notes

**Closed** 2024-04-29 15:42 UTC
Labels: enhancement
