### ISSUE TITLE
Traits should allow methods with generic return types

### ISSUE THREAD

**Issue by grasshopper47** [noir-lang/noir#3474] opened 2023-11-10 12:37 UTC
### Aim

Currently it is possible to use generics within a trait:

```rust
trait Extensions
{
    fn generic<N>(self : [u8], right : [u8; N]) -> bool;   // OK
}
```

### Expected Behavior

A trait allows methods with a generic _return_ type:

```rust
trait Extensions
{
    fn generic<N>(self) -> [u8; N];                    
}
```

### Bug

When creating the implementation the compiler throws a confusing error:

```rust
impl Extensions for [u8]
{
    pub fn generic<N>(self) -> [u8; N] // error: Expected type [u8; N], found type [u8; N]
    {
        // .. //
    }
}
```

Linked issue: https://github.com/noir-lang/noir/issues/3502

### To Reproduce

Compile the following:

```rust
trait Extensions
{
    fn generic<N>(self) -> [u8; N];                    
}

impl Extensions for [u8]
{
    pub fn generic<N>(self) -> [u8; N] // error: Expected type [u8; N], found type [u8; N]
    {
        // .. //
    }
}
```

### Installation Method

Binary

### Nargo Version

0.19.2

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment] 2024-01-02 13:16
Closing as duplicate of https://github.com/noir-lang/noir/issues/3479

**Comment by TomAFrench** [comment] 2024-01-02 13:17
Reopening as they're actually slightly different.

**Closed** 2024-01-16 19:46 UTC
Labels: bug
