### ISSUE TITLE
`comptime_recursion_regression` doesn't codegen assert

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1668] opened 2023-06-13 15:36 UTC
### Aim

The following program:
```rs
fn main(x: Field, y: Field) {
    let flag = (x == 1) | (y == 2);
    assert(flag | false == flag);
}
```
Should code gen an SSA IR containing a constrain instruction. 

### Expected Behavior

^

### Bug

No constrain instruction appears:
```
Initial SSA:
fn main f0 {
  b0(v0: Field, v1: Field):
    v3 = eq v0, Field 1
    v5 = eq v1, Field 2
    v6 = or v3, v5
    return 
}
```

(Note that the program goes on to prove and verifiy for the wrong reason.)

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment] 2023-06-13 15:41
Similarly, `assert(flag | (flag == false))` would also always be true but I don't think the SSA refactor is smart enough to figure that out.

**Comment by jfecher** [comment] 2023-06-15 16:33
Worth noting the old ssa optimizes out the constrain for `comptime_recursion_regression` as well. Its final output is
```
overflow:
************* Block n.0
Assumption:AssumptionId(Index { index: 0, generation: 0 })
6: eq x, 1
8: eq y, 2
9: or (6), (8)
```
Similarly, the old ssa optimizes out the final constrain in 2_div as well.
I think we can close this issue since this is an intended optimization.

**Comment by joss-aztec** [comment] 2023-06-15 16:39
Ah, good point.

> Similarly, assert(flag | (flag == false)) would also always be true but I don't think the SSA refactor is smart enough to figure that out.

Since we don't yet know why the new SSA is eliminating, perhaps we should leave this open until we know it's not happening for the wrong reason.

**Comment by jfecher** [comment] 2023-06-15 16:47
> Since we don't yet know why the new SSA is eliminating, perhaps we should leave this open until we know it's not happening for the wrong reason.

This isn't an issue with SSA, the `(a | b) == c` parsing is from the operator precedence in the parser where `==` has a lower precedence than `|`. If we don't think that is a good default for `|`'s precedence we can discuss that but I think it warrants a separate issue on operator precedence rather than this issue focused on the ssa refactor.

**Closed by jfecher** 2023-06-15 16:47 UTC
Labels: bug, refactor, ssa

**Comment by joss-aztec** [comment] 2023-06-15 16:50
Right, I'm with you now.
