### ISSUE TITLE
Consider introducing `BrilligFunctionPointer` into ACIR

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3907] opened 2023-12-21 18:58 UTC
### Problem

Currently we inline the bytecode into ACIR for each ACIR call.

A brillig opcode in ACIR will therefore contain the bytecode to be executed. This is a problem because if the same Brillig function is called N times, we will be duplicating the bytecode for that function N times.

### Happy Case

We can store the bytecode in an ordered set and replace the bytecode for Brillig in the ACIR opcode, with a pointer to that ordered set.

If the same function is called multiple times, we only duplicate the pointer/index to the ordered set.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment] 2023-12-21 18:59
When we want to have ACIR functions, this might be a good way to do it too instead of inlining the ACIR into ACIR

**Comment by TomAFrench** [comment] 2023-12-22 14:32
Duplicate of #2936

**Comment by vezenovm** [comment] 2024-03-04 16:18
This feels like something that can be handled with this general solution: https://github.com/noir-lang/noir/issues/4428

**Comment by TomAFrench** [comment] 2024-03-06 12:56
Agreed, I'm going to assign this to you and we can close it at the same time as when we handle the folding case.

**Comment by vezenovm** [comment] 2024-04-08 18:32
> It just occurred to me that we should potentially still keep brillig and ACIR separated

Yup agreed

**Closed** 2024-04-16 19:51 UTC
Labels: enhancement
