### ISSUE TITLE
ECDSA behaves differently with non-constant arguments

### ISSUE THREAD

**Issue by dndll** [noir-lang/noir#3888] opened 2023-12-20 10:30 UTC
### Aim

Verify an ECDSA signature that was passed in as a set of `Fields`. Concatenate the parts into the signature so it can be used in  the black box function for K256 ECDSA verification.

### Expected Behavior

Verify signature with the same result as acvm without the circuit panicking.

Ideally, VM black box functions that require arrays should have interop counterparts to derive the array from a field OR the integer with the size required for the array. This is to avoid any magic that happens in the circuit -> VM step.

### Bug

Verifying an ECDSA signature that has been verified by the VM directly.

There is some semantic difference between passing a constant array over an array built in the circuit. I tried various tricks of verifying the joined array with the constant array and confirmed in the circuit that they are the same; however, the underlying VM behaves differently with this variable over the const variable. The VM panics after verifying the signature.

### To Reproduce

1. Clone https://github.com/dndll/GhostFi/tree/nargo-signature-bug
2. Ensure branch is `nargo-signature-bug`
3. Go to circuits/apply and `nargo prove`
4. Operation `0x02` is the signature verification, you should now see:
```
0x01
true
0x02
true
done
The backend encountered an error: "backend_binary: /home/runner/work/aztec-packages/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/primitives/bigfield/bigfield_impl.hpp:1307: static bigfield<Builder, T> proof_system::plonk::stdlib::bigfield<proof_system::UltraCircuitBuilder_<arithmetization::Ultra<barretenberg::fr>>, secp256k1::Secp256k1FqParams>::mult_madd(const std::vector<bigfield<Builder, T>> &, const std::vector<bigfield<Builder, T>> &, const std::vector<bigfield<Builder, T>> &, bool) [Builder = proof_system::UltraCircuitBuilder_<arithmetization::Ultra<barretenberg::fr>>, T = secp256k1::Secp256k1FqParams]: Assertion `(remainder_1024.lo == uint512_t(0))' failed.\n"
```

[The signature was created and verified by acvm here](https://github.com/dndll/GhostFi/blob/master/bin/prover-monolith/src/prover.rs#L325)

### Installation Method

Compiled from source

### Nargo Version

noirc version = 0.19.4+4d133c50a50f21ca23861a9d1987207bd8783d36

### Additional Context

Built nargo from source with the flake [like so](https://github.com/dndll/GhostFi/blob/nargo-signature-bug/flake.nix#L30)

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment] 2024-01-16 13:10
Thanks for opening this issue @dndll!

I can reproduce the error that you're getting using the hardcoded signature + pubkey that you've written into the circuit. Although, looking at the generated ACIR, the output is correct for the Noir source you've provided.

The issue is then either going to be somewhere in how you're generating your inputs or in our proving backend. That said, I'm unable to run your repo to verify how you're generating these inputs.

```
@TomAFrench ➜ /workspaces/GhostFi (master) $ cargo build
    Updating crates.io index
    Updating git repository `https://github.com/noir-lang/noir.git`
error: no matching package named `parity-secp256k1` found
location searched: registry `crates-io`
required by package `near-crypto v0.13.0`
    ... which satisfies dependency `near-crypto = "^0.13"` of package `near-sdk v4.0.0`
    ... which satisfies dependency `near-sdk = "=4.0.0"` of package `near-contract-standards v4.0.0`
    ... which satisfies dependency `near-contract-standards = "^4.0.0"` of package `ghostfi v0.1.0 **(/workspaces/GhostFi/contracts/register)`**
```

Can you provide a public key (x,y components), signature (r,s components) and message hash which you think should generate a valid proof as hex strings? We can then test this on the backend directly.

**Comment by TomAFrench** [comment] 2024-02-15 14:20
Closing as dupe of #3636

**Closed by TomAFrench** 2024-02-15 14:20 UTC
Labels: bug
