### ISSUE TITLE
Support specifying generics on a type when calling an associated function

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#6000] opened 2024-09-11 13:51 UTC
We currently do not allow applying a turbofish to a struct type, attempting to do so will result in a `UnsupportedTurbofishUsage` error

```noir
struct Foo<T> {
    x: T
}

impl <T> Foo<T> {
    fn new(x: T) -> Self {
        Foo { x }
    }
}

fn main() {
    let _ = Foo::<i32>::new(1);
}
```

We should implement support for the turbofish syntax in this situation.

**Comment by asterite** [comment] 2024-09-16 19:51
I think this is a duplicate of #5584

I added support for parsing the turbofishes in the middle of paths but implementing this particular case is kind of tricky.

**Closed** 2024-10-29 16:58 UTC
Labels: enhancement
