### ISSUE TITLE
Compile time operations on comptime variables

### ISSUE THREAD

**Issue by curryrasul** [noir-lang/noir#1853] opened 2023-07-04 03:33 UTC
### Problem

I was working on a custom Merkle tree circuit, and I parameterized it with const/comptime generic `DEPTH`.
However one component/variable had to be an array of `DEPTH + 1` elements. So it seems like constant operations are not supported.

### Happy Case

global A: Field = 1;
global B: Field = 1;

global C: Field = A + B; // C = 2, processed during compile-time

or

global C: Field = 1 + 1; // C = 2, processed during compile-time

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment] 2023-07-04 04:47
This is a duplicate of https://github.com/noir-lang/noir/issues/1734 which goes into some detail on why we currently don't have this. (I agree that we should support this in future however)

**Closed by TomAFrench** 2023-07-04 04:47 UTC
Labels: enhancement
