### ISSUE TITLE
Prover fails to generate proof on simplified mastermind example

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#341] opened 2022-09-26 14:54 UTC
The mastermind example is seen here: https://github.com/vezenovm/mastermind-noir/blob/6eb996afaf7aae351ab914896eab8f5198627861/circuits/src/main.nr#L21

That LOC has been replaced with: `constrain (guess[i] <= 9) & (guess[i] != 0) & (soln[i] <= 9) & (soln[i] != 0);` which gives the following error:

```
Error thrown: Error: WASM function standard_example__get_circuit_size aborted, error: RuntimeError: memory access out of bounds
thread 'main' panicked at 'range start index 224 out of range for slice of length 0', library/core/src/slice/index.rs:52:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::slice::index::slice_start_index_len_fail_rt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/slice/index.rs:52:5
   3: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
   4: core::intrinsics::const_eval_select
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/intrinsics.rs:2376:5
   5: core::slice::index::slice_start_index_len_fail
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/slice/index.rs:42:9
   6: aztec_backend::acvm_interop::proof_system::remove_public_inputs
   7: aztec_backend::acvm_interop::proof_system::<impl acvm::ProofSystemCompiler for aztec_backend::acvm_interop::Plonk>::prove_with_meta
   8: nargo::cli::prove_cmd::run
   9: nargo::cli::start_cli
   ```
   
   One possible reason would be that the compiler is producing invalid ACIR

**Comment by kevaundray** [comment] 2023-01-21 19:14
@vezenovm can this be closed?

**Comment by vezenovm** [comment] 2023-01-23 19:10
The line `constrain (guess[i] <= 9) & (guess[i] != 0) & (soln[i] <= 9) & (soln[i] != 0);` causing an error is an issue that was fixed a little while ago when I was working on the join-split circuit. A circuit with this line can be successfully proven and verified using nargo now. 

However, I am getting a new error that is related to needing the typescript packages in line with Noir changes.  
```
  Mastermind tests using typescript wrapper
panicked at 'called `Result::unwrap()` on an `Err` value: Syntax("unknown variant `BlackBoxFuncCall`, expected one of `Arithmetic`, `Range`, `And`, `Xor`, `GadgetCall`, `Directive`")', crates/acir/src/circuit/mod.rs:30:9

Stack:

Error
    at module.exports.__wbg_new_693216e109162396 (/Users/maximvezenov/Documents/dev/noir-projects/mastermind-noir/node_modules/@noir-lang/noir_wasm/noir_wasm.js:200:17)
    at wasm://wasm/00a338b6:wasm-function[1174]:0x23df72
    at wasm://wasm/00a338b6:wasm-function[2493]:0x272dde
    at wasm://wasm/00a338b6:wasm-function[1715]:0x264aba
    at wasm://wasm/00a338b6:wasm-function[1796]:0x268231
    at wasm://wasm/00a338b6:wasm-function[2218]:0x2715fb
    at wasm://wasm/00a338b6:wasm-function[2043]:0x26e9c4
    at wasm://wasm/00a338b6:wasm-function[2155]:0x270969
    at wasm://wasm/00a338b6:wasm-function[1845]:0x269c14
    at wasm://wasm/00a338b6:wasm-function[1350]:0x24e3aa
```
We could close this issue as the line in question is not the cause of the error and rather a mismatch in the Noir source and typescript wrappers. This is also related to issue #662, where we have a bug that is fixed in the Noir source, but is not reflected in the Noir binaries or Noir dependents.

**Comment by kevaundray** [comment] 2023-01-23 21:15
Okay let's close then

**Closed** 2023-01-23 21:15 UTC
Labels: bug, ACIR, compiler
