### ISSUE TITLE
compile error with generic function: cannot find type parameter in scope

### ISSUE THREAD

**Issue by f01dab1e** [noir-lang/noir#2424] opened 2023-08-24 16:18 UTC
### Aim

```rust
fn hello<N>() {
    for i in 0..N {}
}
```

### Expected Behavior

The code should compile successfully since the generic type parameter N is correctly defined in the function signature.

### Bug

When trying to compile a function with a generic type parameter, the compiler reports that it cannot find the type parameter N within the scope, even though it should be correctly defined.

```
error: cannot find `N` in this scope 
   ┌─ array.nr:97:17
   │
97 │     for i in 0..N {}
   │                 - not found in this scope
   │
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

Compiled from source

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment] 2023-08-24 16:22
I think the issue is in how we identify/infer numeric type variables currently. They're only added to scope if after checking the function signature we can actually confirm they're numeric by finding them in an array length somewhere.

**Comment by Savio-Sou** [comment] 2024-02-23 18:09
@f01dab1e is this still relevant?

**Comment by TomAFrench** [comment] 2024-04-04 17:46
Duplicate of https://github.com/noir-lang/noir/issues/4633

**Closed by TomAFrench** 2024-04-04 17:46 UTC
Labels: bug, good first issue
