### ISSUE TITLE
`bit_shift_comptime` panics in debug mode

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2745] opened 2023-09-18 14:53 UTC
I'm getting a panic on these lines when compiling `bit_shift_comptime` in debug mode.

https://github.com/noir-lang/noir/blob/36dcd4883313faabefe201be3645dcad79dc7970/compiler/noirc_evaluator/src/ssa/acir_gen/acir_ir/generated_acir.rs#L454-L456

**Comment by TomAFrench** [comment] 2023-09-18 15:21
The minimal reproduction is 

```rust
fn main() {
    let a: u1 = 1 >> 1;
    assert(a == 0);
}
```


This gets compiled down to
```
acir fn main f0 {
  b0(v0: u64):
    v10 = div u1 1, Field 2
    constrain v10 == u1 0
    return 
}
```

We should be able to compile this down to an empty circuit. The issue is that when we try and simplify `1 >> 1` we assume that `rhs` conforms to the same max number of bits as `lhs`. This means that when we truncate the `rhs` down to `bit_size` then 2 gets truncated down to zero.

https://github.com/noir-lang/noir/blob/36dcd4883313faabefe201be3645dcad79dc7970/compiler/noirc_evaluator/src/ssa/ir/instruction.rs#L783-L800

We're then always performing a division by zero.

**Comment by guipublic** [comment] 2023-11-29 08:58
I cannot reproduce this issue, so I close it.

**Closed by guipublic** 2023-11-29 08:58 UTC
Labels: bug
