### ISSUE TITLE
cannot find src directory in path for any 

### ISSUE THREAD

**Issue by onurinanc** [noir-lang/noir#2394] opened 2023-08-22 09:36 UTC
### Aim

Trying to add dependency, but whether there is a src or not it gives this "cannot find src directory in path" error

### Expected Behavior

Add dependency

### Bug

Trying to add dependency, but whether there is a src or not it gives this "cannot find src directory in path" error

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

nargo 0.9.0 (git version hash: 970c18ee29e37d35e39169005e629deed8b30b6e, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment] 2023-08-22 10:12
Can you add a example to allow reproduction please?

**Comment by onurinanc** [comment] 2023-08-22 10:48
Step 1. git clone https://github.com/onurinanc/noir-bn254/
Step 2. Go into Nargo.toml
Step 3. Add dependency bigint = {tag = "", git = "https://github.com/onurinanc/noir-bigint"}
Step 4. nargo test

**Comment by TomAFrench** [comment] 2023-08-22 12:04
Why are you providing an empty entry for `tag`? If you place `tag = "master"` then does the dependency work?

**Comment by onurinanc** [comment] 2023-08-22 12:29
@TomAFrench No, it doesn't work. It gives the following error "cannot find src directory in path /home/onurinanc/nargo/github.com/onurinanc/noir-bigint/main" (main or master)

**Comment by phated** [comment] 2023-09-15 18:10
Nargo has changed drastically since this opened. We now require package names, have all of the logic for workspaces, etc. 

I'm going to close this as solved but feel free to re-open if you update your nargo version and make updates to the project and it still happens.

**Closed by phated** 2023-09-15 18:10 UTC
Labels: bug, P-HIGH
