### ISSUE TITLE
"if" without "else" passes type checking

### ISSUE THREAD

**Issue by f01dab1e** [noir-lang/noir#1942] opened 2023-07-17 10:42 UTC
### Aim

```
fn main() {
    let _a = if false { true };
}
```

### Expected Behavior

type checking error: expected `bool`, found `()`

### Bug

```
❯ nargo execute
The application panicked (crashed).
Message:  No element at index
Location: crates/noirc_evaluator/src/ssa/context.rs:400
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

Compiled from source

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment] 2023-07-17 16:00
> type checking error: expected bool, found ()

Returning `()` for an if without else is intended. I actually wasn't aware that rust errors if you try to use it as an expression.

I can't seem to replicate the crash you got afterward though.

**Comment by jfecher** [comment] 2023-07-17 16:29
Okay, I'm not sure what I got different last time but I ran it again and was able to reproduce your error.

Since this is only occuring with the current SSA code, and is fixed in the new ssa (which you can enable with `--experimental-ssa`), I'm going to close this issue.

**Closed by jfecher** 2023-07-17 16:29 UTC
Labels: bug
