### ISSUE TITLE
Cost analysis for custom Plonk Gates

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#164] opened 2022-02-09 17:35 UTC
We should check the cost of custom Plonk Gates, namely:
- Range gate
- And gate
- Xor gate

Although they are more efficient than their arithmetic counterpart, it may not be true in all cases, for instance with 1-bit inputs.
We should know what is the cost depending on the input size so that Noir can decide what is best to use.
When there is no advantage, arithmetic version can provide more opportunities for simplification.

**Comment by kevaundray** [comment] 2023-01-21 18:11
This seems like something we want to upstream to ACIR ie functionality where the proving system tells us how expensive an opcode is relatively speaking.

The problem is that this is non-trivial; the cost needs to be measured in something like field element complexity.

I'll close this and opt to reopen an issue in ACIR and the Aztec backend

**Closed by kevaundray** 2023-01-21 18:11 UTC
