### ISSUE TITLE
Implement support for operator overloading in the comptime interpreter

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#5328] opened 2024-06-25 17:34 UTC
We have a TODO to support operator overloading in the interpreter. We should resolve this and implement this feature.

https://github.com/noir-lang/noir/blob/b3a2c9c86bea8d287fc024090087f3b66bbc31a4/compiler/noirc_frontend/src/hir/comptime/interpreter.rs#L610-L614

**Comment by jfecher** [comment] 2024-06-25 17:35
Duplicate of https://github.com/noir-lang/noir/issues/4925

**Closed by jfecher** 2024-06-25 17:35 UTC
