### ISSUE TITLE
0xa3dad654 POINT_NOT_ON_CURVE after upgrade from 0.22.0 to 0.25.0

### ISSUE THREAD

**Issue by peter0x2** [noir-lang/noir#4607] opened 2024-03-21 13:41 UTC
### Aim

NextJs project upgraded to 0.25.0 and get error POINT_NOT_ON_CURVE (0xa3dad654) when calling verifier contract.
The code is working in 0.22.0
nextJs depenencies are:
    "@aztec/bb.js": "^0.30.0",
    "@noir-lang/backend_barretenberg": "^0.25.0",
    "@noir-lang/noir_js": "^0.25.0",
    "@noir-lang/noir_wasm": "^0.25.0",
    "@noir-lang/types": "^0.25.0",

"noir_version":"0.25.0+3f676051a6073d6eabdc7fee68e4b522334344f6"``

### Expected Behavior

Both proof geneartion and contract verifiing is working as 0.22.0 after upgrading to 0.25.0

### Bug

transaction reverted with code 0xa3dad654, trace in hardhat as below:
(0xb6aa91e8904d691a10372706e57ae1b390d26353).verify(_proof: 0x30213f300f074f4a8696d0ef312444f294677a1102f00069ce488b9d14013be20c72d6c2319e52c833ce997126de7703b7934f95f32ab800ee1843ec1e439e352d181a1a431214bee9edacad12c91fc51474c8d11b3eee6e4086727f6319d1ff203549622e62af1e9af3ae0c5d80be43aba8cdda55f7240564de96f6d41ead402d56ee70d98768574f941190d2bc7b5d40f44b965914c47b4f8fa565975c457d180f5ee25b64c7fede7b731cbe187004ac647b12e339e3dddd82107fe532c409021df39835624e294dcfc3f2f951da5cde298d1e982527767d7f074cdcb8ef4913564f876877260d7b57d5310d6d60ffe7ef87367900ce119b8f42a405172f771a341fdab8a680c841347ccf7b5bf14549059791309f56cd7ffbdc844410cc2a264a9ba588dad469079aab3812da318c5c1e35a7a3be3c91fbc08af4fa008050055f5c48f2eae9c141de861e85597152f4b339a7430e9efdccfed530abca862206c06424a49c2409260ba721686cd4f51176aac470f9eb89a9c7aa2522a037192fed7cfe8cd85d3194301630172a8b216a6dc4c5bb42b4a6ca41be7df936d6b51cf9aa723f95b5beca27967d05651444220087258348c5c0d344a5e58e1717181a91915e7e6b52754f46a6df38c3c47aea890f56cdc2291cd433150acfe9cde425601e6136e2eb3963a3f1dbfaa9df16d39fd80b3b33a27fe399d84f8dedd47b279ee01676ebeba1d5ab17a63e58687430770cc56a3c0ca2298063043478a35d121bf0b171e0ff25b510530d357603e0f54fdbc12c8aa83d9b830b0764a0976a11024205713732f607a4d06fc3329db4e8d3c1402f30034981689e3dcba05eb8147f4addf8a09702deaeaf6b686c58a6bfdd14d294b9e2cc1eceab04e7b5bbc83016b2ff29986f63bffb888658554688a0a0bfc6ab4e9d7da5988d33481e4fdf2f3a18cc4d8965f525b0e9ea55fcb622c2b2c4dfc70c8576d9804f1db16a324a12ef1c4c4730db85cc17be4c51be6b63efaf462b91beb056867d68b5fd620a9b2b8efda7920c5e44c9b3863cf475852b4a623e422e748bf5a94e7e78a00c3a3c2c508c1e57f7058cc1fb3228a1869ed6036867aace4281150f5c3bfe282664ce2b0daee84fe2cf06c1293e5791fa34f7ccf78e723dcf739a181d84a549bb98e62f78e118eef52ef47f7fd74384aacdf6f57929f32c4377af1bdabac40eabe4fd1617d45e596c6785ebca09d8441e104a12e83a986f4cf4ad1e313bff4b37675621ef5b3b78310484b7a6b5110fdc9e61336639bada7853614818d50fe78e9f100a3f7bc809829da24b4ceb28ce69eef31ca2e62b0d5a73109c77271f40ceef3b0b8a8962005f2bc139f29e6509b6678467df0b07b699347482a69e1a71f8942304f5ee1f835c1c5ae8baf7d40f6e3afde757e44d08817853c6816608937d4b8328e6c9fea69c19fcdfb20c36e5b5b673c1ac7b21310ab04a1976787d1252754525dc14ff0325d04758fb50a8e0e4f1c335d4173366c8e5c9b476e1c165bd55c92cb325e4cf42963532968ca755df6bc08f5f8414537ee8374e6189988556ca3f08d5d1815d5ff857b5e80216c579a90dc7ac9a9a6b8088dc32b8015f6d310d792e02ac40b08387a01e60ca20ac9525d47931f8b834510cefbbc246e0e3bf33d61af6ece22337373d8da357922ae9bb83187588c757131efd752f0f7bad3133c122896516b84e0786c1440de962c7a9dc14ce27358180306114f195f846ed1d4706522e7f8a494e167e8adf7148be4906b24faa8e2d2062e84bcdf2f5dbe70f27122faf0c43709381b3f0eaaff4e3cecd95f556b788166a1336d19281d60363c30c1fa282041498e5f6d38ff21f35782bb572a60fb6e2785c24950c31207915f9267a9d2da839d95c5379bac51b5d83e07f72038e77eeec5c95d6177f428c00cf0c87479e385e98c1f1c2da1b5773a7d88a045f9f5ff6bf49efb4e846a8ef75d10e9e6bbb27667f16de519a01076009e493df163be861092f3ca38bfc868daf8b02b69f919f719a30cdc8e45747696378cb11de86a6596b62165616deda1c3e272819b3df475f3a18b01f5f0da5aa07f20eb780a26b18c132d32a6e8a1143caaf1ecf9726c6b33b42399b50610cd926f512ac216781d62d68ddb6481c19e67a1d1b02908456ce2d592fec76b37868e7bf3580c0d55a9fdc7b38cfb124a92159f322545b1c51284a03cde1baa1fd6a66cced9beb67c546d9914fe2fae9eee8dc3f253d504a462d582f2a00b3f52378987c195c6bd0586f5db41ca918a89af4b4e2190d1767e017e50ad57291633678f39b2634d49fce5379bc42a3307c2cb4d58002c4e6eb0c9b309bd41a07d4d73c4e3132a77eaa1dda5a24814f7aefc2a1d68d0b8fdd6fb51e8fe38ce33b8f166105a9ff8ed9da7e5139343fa41108f345b3f0152bab2d0d4a3cb9370d8d755eaa2a003a93e0c10e04f9be5551c31c5d9b2ed12a61a575b3524912b75787dc2effe4e145177cbdc327a5dff004c1f77481c72c24e73704a2b6009c727b9958594fdacd5496fe8b186921359c93e3103a96f98f25b2beaea41137ef3eec50f93678970edf5555eec0a8e98a1815cff07a73ce4811c531a167d581d1ebfd50234000bf12c71bca6827b57ca0bb50092461e521fb17bda6c33c82753d7a29bd17789d6039a235727983ccdcd6a81744d2add23bf82b67f1ffe8dff09ec934fe50c2a52469db1da179011f5f69189907c1d6a2e62409c004bc196045b6d3338c993327639ad6de2d810b2fa396e6fe9edc14572e681e7f7179c1ff7973b9ece701bac98b846969fff0511523f25b6ffa92d74bee791c0a83f4ec8c0b4e417fb45e2dee5ea35d695e46499e929895772e2f23d0bbaa1fa959bd54aaa769a0986883fed5ce926d96253c49c7e0083fa98b7ed5ed49c12d5af1272e9638577e7c6347c7d63714414fa0588f752394dfca8fbdb8edf66011b00d1c19e9d91bca654d3ea044c049f5215af82d7592ba998cf64d9d0f685d, _publicInputs: [0x1acd8c7346146404998bcf6fa5e6b34ee7d0954cd062bb444250a895f94b2a5b, 0x0f230be3c7d8398fccc47ba447901d8bb33f97dc59ecd38c3fb2016811d4d420, 0x00f8d63b729f9d69633e0138e9bb522b7902f3869fa937a65d483d0e22a5dd84, 0x0000000000000000000000000000000000000000000000000de0b6b3a7640000])
      [STATICCALL] Precompiles.modexp(input: 0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000201c6ca452fd09e8a6d847223453a92a1b2ceb9b2340c404a175aa731e8822151a30644e72e131a029b85045b68181585d2833e84879b9709143e1f593efffffff30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001) → (0x1a9d45eafd2c3ec195c4054ecbcd78dd6e91857a66d7c9e425442371d652a193)
      [REVERT] POINT_NOT_ON_CURVE()
   [REVERT] POINT_NOT_ON_CURVE()

### To Reproduce

1.
2.
3.
4.

### Project Impact

Blocker

### Workaround

None

### Installation Method

None

### NoirJS Version

0.25.0

### Would you like to submit a PR for this Issue?

None

**Comment by vezenovm** [comment] 2024-03-21 13:49
Could you provide a reproduction? It would help us debug as our tests for proof generation solidity contract verification are working. If you have changed your circuit at all make sure that you also have updated your contract.

**Comment by peter0x2** [comment] 2024-03-21 15:19
I've done the followings:
1. noirup to 0.25.0
2. regenerate circuits json and verifier contract with the 0.25.0 compiler
3. update nextjs project with the latest circuits and change dependency to 0.25.0 and update to call noir.generateProof
4. update contracts to the latest one
5. open browser to trigger the proof generation and calling the contract
6. failed 

The code is working fine when I'm runing unit test via "hardhat test" calling the same proof generation code and verifier contract

**Comment by peter0x2** [comment] 2024-03-22 01:37
It is working in incognito window

**Comment by peter0x2** [comment] 2024-03-22 02:26
After I remove the g1Data in indexdb, the normal window is working.

**Comment by TomAFrench** [comment] 2024-03-25 10:52
This is not debuggable without any code I'm afraid so I'm going to close this issue. If you can provide some reproduction code then we can take a look however.

I'd recommend clearing both g1 and g2 data as it looks like the issue is in your CRS.

**Closed by TomAFrench** 2024-03-25 10:52 UTC
Labels: bug
