### ISSUE TITLE
Add return type into the ABI

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#633] opened 2023-01-12 21:40 UTC
# Problem

The ABI currenlty only specifies parameters and not the return types from the functions. This is not a big problem as we use the "return" parameter to denote the output. Assuming there are no other parameters named "return" this is safe. 

# Solution

We can add another field in the ABI Parameter field called "return" and put the return type there instead.

# Alternatives considered

(Describe any alternative solutions you have considered.)

# Additional context

(If applicable.)

**Comment by TomAFrench** [comment] 2023-01-31 17:36
This is a duplicate of #678. Closing this issue as the other has more detail.

**Closed by TomAFrench** 2023-01-31 17:36 UTC
Labels: enhancement
