### ISSUE TITLE
`comptime` interpreter fails to perform slice equality

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#5273] opened 2024-06-18 12:57 UTC
The below program fails with the error message below.

```rust
fn main() {
    comptime {
        assert_eq(&[1], &[1]);
    }
}
```

```
error: No implementation for `[Field]` == `[Field]`
  ┌─ /home/tom/Programming/aztec/noir/test_programs/compile_success_empty/comptime_as_slice/src/main.nr:6:9
  │
6 │         assert_eq(&[1], &[1]);
  │         ----------------------
  │

Aborting due to 1 previous error
```

**Comment by jfecher** [comment] 2024-06-18 13:29
Duplicate of https://github.com/noir-lang/noir/issues/4925

**Closed by jfecher** 2024-06-18 13:29 UTC
