### ISSUE TITLE
It's impossible to test recursive circuits in nargo

### ISSUE THREAD

**Issue by LogvinovLeon** [noir-lang/noir#5004] opened 2024-05-09 12:09 UTC
### Aim

I'm trying to build a system that leverages recursive proofs and I want to be able to test it.

### Expected Behavior

* `nargo test` that calls `verify_proof` with invalid values - fails
* `nargo prove` that calls `verify_proof` with invalid values - does not panic but shows a reasonable error message that recursive proof is invalid

### Bug

```sh
nargo prove
The backend encountered an error: "libc++abi: terminating due to uncaught exception of type std::runtime_error: Trying to invert zero in the field\n"
```
```sh
nargo test
[recursive] Running 1 test function
[recursive] Testing simple... ok
[recursive] 1 test passed
```

### To Reproduce

Here is the code:
```rs
use dep::std::{unsafe::zeroed, verify_proof};

struct RecursiveProof {
    key_hash: Field,
    verification_key: [Field; 114],
    proof: [Field; 93],
}

global key_hash: Field = zeroed();
global verification_key: [Field; 114] = zeroed();
global proof: [Field; 93] = zeroed();

fn main() {
    verify_proof(
        verification_key.as_slice(),
        proof.as_slice(),
        [].as_slice(),
        key_hash
    );
}

#[test]
fn simple() {
    verify_proof(
        verification_key.as_slice(),
        proof.as_slice(),
        [].as_slice(),
        key_hash
    );
}
```

The proof is obviously invalid, but it's important for `nargo` to handle invalid proofs too as testing needs to have failure cases also, not just the happy-case.

1. Run `nargo test`
2. Run `nargo prove`

### Project Impact

Blocker

### Impact Context

This is very important for us as it blocks us from writing integration tests in `nargo`.
This forces all the testing to happen on the latest stage as E2E tests which is more complex & pricey and also results in less robust/tested/secure systems

### Workaround

Yes

### Workaround Description

Test `verify_proof` on E2E level. Use only correct proofs in integration tests in `nargo`.
This approach still has a big problem that integration tests for invalid proofs pass, so one needs to be super careful.

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.28.0

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment] 2024-05-09 15:01
This isn't something that nargo can pick up on as in order to determine whether a proof is valid or not requires it to be verified by the backend. `nargo test` doesn't/won't have access to the backend and so it's impossible for it to validate these proofs.

This is shown in the warning printed when compiling a program which uses the `verify_proof` function.
```
verify_proof(...) aggregates data for the verifier, the actual verification will be done when the full proof is verified using nargo verify. nargo prove may generate an invalid proof if bad data is used as input to verify_proof
```


In order to test how systems of recursive proofs work together, e2e tests are the way to go.

**Comment by LogvinovLeon** [comment] 2024-05-10 08:24
Is there any reason - why `nargo test` can't use the backend while `nargo prove` can?
The backend get's installed together with `nargo` so it's safe to assume that it's available on the user's machine while running `nargo test`.
One can use this command to determine the name of the currently installed backend
`nargo backend current`

**Comment by TomAFrench** [comment] 2024-05-10 12:26
The reasoning is that `nargo test` should only test whether the circuit is satiable within the ACVM, and as the ACVM is unaware of the proving backend being used then it cannot determine whether the proof being passed in is valid or not. 

We're actually in the process of removing backend interactions from nargo (#4960) in general so that `nargo` is only responsible for compilation, execution, and testing of Noir source code.

**Comment by TomAFrench** [comment] 2024-05-10 17:04
Closing as this is expected behaviour.

**Closed by TomAFrench** 2024-05-10 17:04 UTC
Labels: bug
