### ISSUE TITLE
Cannot compile "bin" package inside of a "lib" package 

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#2362] opened 2023-08-17 22:46 UTC
### Aim

Attempting to generate a proof for the program laid out in issue: #2133. 

### Expected Behavior

I should be able to execute a project with a "bin" package type that is a subdirectory of a root "lib" project. 

### Bug

```
Error: Package `noir_trie_proofs` has type `lib` but only `bin` types can be compiled

Location:
    crates/nargo_cli/src/cli/mod.rs:79:5
```

### To Reproduce

1. `git clone https://github.com/aragonzkresearch/noir-trie-proofs`
2. `cd noir-trie-proofs/tests/depth_8_storage_proof`
3. `nargo execute` or `nargo compile`

### Installation Method

Compiled from source

### Nargo Version

nargo 0.10.3 (git version hash: 11bbd6103cce9615c937600f0e0ff39a6af35233, is dirty: true)

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment] 2023-11-02 20:57
Closing as duplicate of https://github.com/noir-lang/noir/issues/2107.

**Closed by Savio-Sou** 2023-11-02 20:57 UTC
Labels: bug
