### ISSUE TITLE
Rust's orphan rule doesn't seem to hold

### ISSUE THREAD

**Issue by nventuro** [noir-lang/noir#5475] opened 2024-07-10 19:11 UTC
### Aim

I'm able to define impls for traits in modules in which neither the trait nor the type are defined. My understanding is that this is illegal (the so-called 'the orphan rule').

### Bug

```rust
mod serde {
    trait Serialize<let N: u32> {
        fn serialize(self) -> [Field; N];
    }
}

use crate::serde::Serialize;

// Even though Field is primitive, this should be illegal - the definition should go inside the serde
// module (where the trait is defined).
impl Serialize<1> for Field {
    fn serialize(self) -> [Field; 1] {
        [self]
    }
}

mod many_field {
    struct ManyFieldStruct {
        a: Field,
        b: Field,
    }
}

use crate::many_field::ManyFieldStruct;

// In this case neither the struct nor the trait have been defined in this module, yet I can still provide
// an impl and break the orphan rule.
impl Serialize<2> for ManyFieldStruct {
    fn serialize(self) -> [Field; 2] {
        [self.a.serialize()[0], self.b.serialize()[0]]
    }
}

#[test]
fn test() {
    let bar = ManyFieldStruct { a: 13, b: 42 };

    let bar_ser = bar.serialize();
    assert_eq(bar_ser[0], 13);
    assert_eq(bar_ser[1], 42);
}
```

I tried wrapping trait with an inner module (i.e. `serde::foo::Serialize`), and then place a second impl for Field there, and got a duplicate impl error, so at least that seems to work as expected.

**Comment by asterite** [comment] 2024-07-22 16:35
I think this is working as expected. The orphan rule seems to be about not allowing these across crates, but here everything is defined in the same crate.

**Comment by asterite** [comment] 2024-07-22 16:35
(put another way: I couldn't reproduce this issue if `mod serde` is in a different crate)

**Comment by asterite** [comment] 2024-07-22 17:36
Closing as this is how it works in Rust too, but feel free to reopen if what I'm saying is wrong.

**Closed by asterite** 2024-07-22 17:36 UTC
Labels: bug

**Comment by nventuro** [comment] 2024-07-22 20:48
Ahh you seem to be right, sorry! For some reason I was sure modules had to contain both definition and impl. This makes much more sense.
