### ISSUE TITLE
Two recursive proofs barely do not fit into WASM limit in new versions of Nargo

### ISSUE THREAD

**Issue by LogvinovLeon** [noir-lang/noir#4874] opened 2024-04-22 13:29 UTC
### Problem

If one wants to verify big circuits in Noir, they need to split them into smaller one to avoid WASM 2**19 limit.
There are two strategies then on how to combine them.
1. Linear
2. Binary tree
The second strategy allows to parallelise the proving, but requires two recursive proofs verifications to be able to fit into the WASM limit. It used to be the case with nargo 0.22.0, but not the case with nargo 0.27.0 because of a small perf regression on verify_proof.

### Happy Case

Would be nice to be able to fit two recursive proofs into 2**19 gates

### Project Impact

Nice-to-have

### Workaround

Yes

### Workaround Description

Don't parallelise prooving

### Would you like to submit a PR for this Issue?

None

**Comment by Savio-Sou** [comment] 2024-04-24 13:33
Thanks for submitting the Issue 🙌 closing as duplicate of https://github.com/noir-lang/noir/issues/4409, follow the discussion there on updates and developments.

**Closed by Savio-Sou** 2024-04-24 13:33 UTC
Labels: enhancement
