### ISSUE TITLE
Blow up when RAM is used in a loop under a conditional (NOT solved by 0.34.0) (EASY WORKAROUND)

### ISSUE THREAD

**Issue by jp4g** [noir-lang/noir#6144] opened 2024-09-24 10:55 UTC
### Aim

I want to conditionally assign the preimage of a `sha256_var` hash

### Expected Behavior

Constraints do not blow up

### Bug

Constraints blow up the same way they did when trying to assign variable length (not constant in var param) sha256_var input in 0.33.0 

### To Reproduce

```rust
// I want to pack items into a sha256 hash
// Assuming 0-padded past `item_x_length`
let item_1: [u8; 64] = ...;
let item_1_length: u32 = 17;
let item_2: [u8; 128] = ...;
let item_2_length: u32 = 100;

// I try directly assigning indexes
let mut preimage = [0; 192];
let mut index = 0;
for i in 0..64 {
    if i < item_1_length {
         preimage[index] = item_1[i];
         index += 1;
    }
}
for i in 0..128 {
    if i < item_2_length {
         preimage[index] = item_2[i];
         index += 1;
    }
}
// blows up constraints
let hash = std::hash::sha256_var(preimage, item_1_length + item_2_length);
```

### Workaround

Yes

### Workaround Description

```rust
// I want to pack items into a sha256 hash
// Assuming 0-padded past `item_x_length`
let item_1: [u8; 64] = ...;
let item_1_length: u32 = 17;
let item_2: [u8; 128] = ...;
let item_2_length: u32 = 100;

// I try directly assigning indexes
let mut preimage = [0; 192];

for i in 0..64 {
    preimage[i] = item_1[i];
}
for i in 0..128 {
    preimage[i + 64] = item_2[i]
}
// expected constraints
let hash = std::hash::sha256_var(preimage, item_1_length + item_2_length);
```

### Additional Context

I know that the working way is actually more efficient anyways but it is forseeable that someone would try to do this pattern. Maybe they figure out they can just assign the way in the workaround, but it is probably in best interest to not totally break unoptimized code patterns

### Project Impact

Nice-to-have

### NoirJS Version

0.34.0

### Proving Backend Tooling & Version

0.55.0

### Would you like to submit a PR for this Issue?

None

### Support Needs

none

**Comment by vezenovm** [comment] 2024-09-26 14:06
> ```rust
> // I want to pack items into a sha256 hash
> // Assuming 0-padded past `item_x_length`
> let item_1: [u8; 64] = ...;
> let item_1_length: u32 = 17;
> let item_2: [u8; 128] = ...;
> let item_2_length: u32 = 100;
> ```

For clarity sake, these are written directly in the program as constants. I'm assuming they come from witness inputs though as that is the only way I was able to reproduce the blow-up. 
e.g. this circuit gave me 267k acir opcodes and 523k backend constraints with `bb gates`:
```noir
fn main(
    item_1: [u8; 64], 
    item_1_length: u32,
    item_2: [u8; 128],
    item_2_length: u32,
) {
    // I try directly assigning indexes
    let mut preimage = [0; 192];
    let mut index = 0;
    for i in 0..64 {
        if i < item_1_length {
            preimage[index] = item_1[i];
            index += 1;
        }
    }
    for i in 0..128 {
        if i < item_2_length {
            preimage[index] = item_2[i];
            index += 1;
        }
    }
    let hash = std::hash::sha256_var(preimage, (item_1_length + item_2_length) as u64);
    println(hash);
}
```
While replacing the preimage assignment to the workaround gives me  7.5k ACIR opcodes and 50.5k backend constraints.

**Comment by vezenovm** [comment] 2024-09-26 14:14
This blow-up looks to be due to the use of RAM gates and not due to sha256_var. This program without a call to `sha256_var` leads to ~260k ACIR opcodes 493k backend constraints:
```noir
fn main(
    item_1: [u8; 64], 
    item_1_length: u32,
    item_2: [u8; 128],
    item_2_length: u32,
) {
    // I try directly assigning indexes
    let mut preimage = [0; 192];
    let mut index = 0;
    for i in 0..64 {
        if i < item_1_length {
            preimage[index] = item_1[i];
            index += 1;
        }
    }
    for i in 0..128 {
        if i < item_2_length {
            preimage[index] = item_2[i];
            index += 1;
        }
    }
    println(preimage);
}
```

**Comment by vezenovm** [comment] 2024-09-26 16:54
This is essentially a repeat of this issue https://github.com/noir-lang/noir/issues/5027 so going to close this one in favor of that one which has more context on possible solutions.

**Closed by vezenovm** 2024-09-26 16:54 UTC
Labels: bug

**Comment by jp4g** [comment] 2024-09-27 06:35
got learnt
