### ISSUE TITLE
Initial Compile Fails During Ignite SRS Download

### ISSUE THREAD

**Issue by jtriley-eth** [noir-lang/noir#1074] opened 2023-03-30 19:27 UTC
### Aim

create and build a noir project, no modifications to the project.

`Nargo.toml`

```toml
[package]
authors = [""]
compiler_version = "0.1"

[dependencies]
```

`src/main.nr`

```noir
fn main(x : Field, y : pub Field) {
    constrain x != y;
}
```

commands executed:

```bash
nargo new lib6502-nr;

cd lib6502-nr;

nargo compile lib6502-nr;
```

### Expected behavior

the download to complete

### Bug

on executing the following command on a fresh project:

```bash
nargo compile lib6502-nr
```

it attempts to download "Ignite SRS" and fails with the following.

> Note: my home directory was replaced with `<home>` in the output.

```
Downloading the Ignite SRS (340MB)

[00:04:59] ######################################## 322560348/322560348 
Downloaded the SRS successfully!
Time Elapsed: 4 minutes

SRS is located at : "<home>/noir_cache/ignition/transcript00.dat"
The application panicked (crashed).
Message:  range end index 322560156 out of range for slice of length 73510288
Location: /Users/runner/.cargo/git/checkouts/aztec_backend-a697fb631cbad807/2cb523d/common/src/crs.rs:37

This is a bug. Consider opening an issue at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### To reproduce

1. `nargo new libname`
2. `cd libname`
3. `nargo compile libname`

(apple m1)

### Installation method

Binary

### Nargo version

nargo 0.3.2 (git version hash: 29b1f7df4d563849a62e64c533cb62932188135b, is dirty: false)

### Additional context

bug occurs on macbook air (m1)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by Globallager** [comment] 2023-04-03 10:03
Hey there, thanks for submitting the Issue!

Could you take a look of https://github.com/noir-lang/noir/issues/1069 and see if your problem encountered was similar?

**Comment by Globallager** [comment] 2023-04-14 06:21
Closing as it seems like a duplicate of https://github.com/noir-lang/noir/issues/615.

Do reopen this issue if the redownloading `transcript00.dat` workaround as suggested in that issue [here](https://github.com/noir-lang/noir/issues/615#issuecomment-1458880678) isn't working for you.

**Closed by Globallager** 2023-04-14 06:21 UTC
Labels: bug
