### ISSUE TITLE
bug: type aliases cannot be used in type namespace

### ISSUE THREAD

**Issue by 0xJepsen** [noir-lang/noir#6276] opened 2024-10-10 17:33 UTC
### Aim

The application panicked (crashed).
Message:  type aliases cannot be used in type namespace
Location: compiler/noirc_frontend/src/hir/resolution/import.rs:290

The functionality broke after i added a function `byte_stream_blocks` which takes an arbitrary length byte array and converts it blocks of 16 4x4 bytes to be used to model aes state. However when writing my test (probably should still fail) i got this panic

### Expected Behavior

The tests should run. 

### Bug

```
The application panicked (crashed).
Message:  type aliases cannot be used in type namespace
Location: compiler/noirc_frontend/src/hir/resolution/import.rs:290

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### To Reproduce

This happened and can be reproduced by running `nargo test` on this [branch](https://github.com/pluto/Noir-AES-GCM/pull/8) 

### Workaround

None

### Workaround Description

pending... 

### Project Impact

Blocker

### Nargo Version

noirc version = 0.33.0+325dac54efb6f99201de9fdeb0a507d45189607d

### Would you like to submit a PR for this Issue?

Maybe

**Comment by jfecher** [comment] 2024-10-11 09:45
Duplicate of https://github.com/noir-lang/noir/issues/4469

The issue is the line:

```noir
let mut blocks = [Block::default(); nBlocks];
```
Where a type alias is used in a path (`Block::default()`). Unfortunately this doesn't work currently and leads to a compiler panic. The workaround for this case would be to `Default::default()` instead. You can also use it for the array as a whole:
```noir
let mut blocks = Default::default();
```

**Closed** 2024-10-11 09:45 UTC
Labels: bug
