### ISSUE TITLE
Incorrect type inference for `bit_not` on unsigned integer

### ISSUE THREAD

**Issue by gladiatorcasino** [noir-lang/noir#2548] opened 2023-09-04 11:32 UTC
### Aim

The return type of the `bit_not` operator is not correctly inferred when used on an unsigned integer.
Given the statement:

```rust
let a: u32 = 3 & !1;
```

The type of `3` is inferred to be `Field`, and the type of `!1` is inferred to be `bool`. Both of these are incorrect. The compiler throws an error message complaining that the `&` operator is operating on two imcompatible types: `Field` and `bool`.

Without the `!1` part, i.e., `let a: u32 = 3 & 1;`, the compiler correctly infers all the data types and the compilation succeeds.

### Expected Behavior

The compiler should correctly handle the bitwise not operator and infer the type as unsigned integer.

### Bug

Run `nargo new bit_not` and replace the contents of `src/main.rs` with the following:

```rust
fn main() {
    let a: u32 = 3 & !1;
}
```

Run `nargo check` and observe the following error message:

```bash
warning: unused variable a
  ┌─ /home/gladiatorcasino/bit_not/src/main.nr:2:9
  │
2 │     let a: u32 = 3 & !1;
  │         - unused variable
  │

error: Expected type bool, found type Field
  ┌─ /home/gladiatorcasino/bit_not/src/main.nr:2:23
  │
2 │     let a: u32 = 3 & !1;
  │                       -
  │

error: Types in a binary operation should match, but found Field and bool
  ┌─ /home/gladiatorcasino/bit_not/src/main.nr:2:18
  │
2 │     let a: u32 = 3 & !1;
  │                  ------
  │

Error: Aborting due to 2 previous errors

Location:
    crates/nargo_cli/src/cli/mod.rs:79:5
```

### To Reproduce

1. Run `nargo new bit_not` and replace the contents of `src/main.rs` with the code above.
2. Run `nargo check`.

### Installation Method

Binary

### Nargo Version

nargo 0.10.5 (git version hash: 9fe4cfd05b46d1d8867bc2583a11da32480366fc, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment] 2024-02-15 14:39
Confirming this issue still exists in master.

**Comment by TomAFrench** [comment] 2024-02-19 09:04
There's a good chance this is fixed by @michaeljklein's recent work. Will check today.

**Comment by asterite** [comment] 2024-07-23 15:35
This seems to be working fine now. I think it's because we now let `!` dispatch to a trait and so `!1` will make `1` be any integer type that supports the `!` operator.

To see the deduced types, with inlay hints:

![image](https://github.com/user-attachments/assets/f1e7ec4e-f2d5-4da0-ac45-d0795f299fe8)

**Comment by asterite** [comment] 2024-07-23 16:23
Reopening to add a regression test.

**Closed** 2024-07-23 17:21 UTC
Labels: bug, compiler frontend
