### ISSUE TITLE
Nargo execute should not panic if an invalid JSON-RPC resolver url is passed

### ISSUE THREAD

**Issue by sirasistant** [noir-lang/noir#3904] opened 2023-12-21 15:12 UTC
### Problem

Nargo panics if an invalid URL is passed to the oracle-resolver arg.

### Happy Case

If the user passes in an invalid oracle resolver url, we likely don't want to panic since its a user error.

### Would you like to submit a PR for this Issue?

No

**Comment by asterite** [comment] 2024-06-24 20:31
I'm working on this but I can't reproduce a panic.

I applied this diff to master:

```diff
index baef0c378..4eb7cfff0 100644
--- a/examples/prove_and_verify/src/main.nr
+++ b/examples/prove_and_verify/src/main.nr
@@ -1,3 +1,7 @@
-fn main(x: Field, y: pub Field) {
+#[oracle(custom_getter)]
+unconstrained fn custom_getter() -> Field {}
+
+unconstrained fn main(x: Field, y: pub Field) {
+    custom_getter();
     assert(x != y);
 }
\ No newline at end of file
```

Then, after compiling nargo_cli, went to `examples/prove_and_verify` and ran this:

```
$ ✗ nargo execute --oracle-resolver foo
warning: Unused expression result of type Field
  ┌─ /Users/asterite/Projects/noir/examples/prove_and_verify/src/main.nr:5:5
  │
5 │     custom_getter();
  │     ---------------
  │

Failed calling external resolver. transport error: minreq: was redirected to an absolute url with an invalid protocol
```

So, I get an error but it doesn't look like a Rust panic. Maybe this is already fixed? 🤔

**Comment by TomAFrench** [comment] 2024-06-25 10:30
Looks like it has! Thanks, we can just close this in that case.

**Closed by TomAFrench** 2024-06-25 10:30 UTC
Labels: enhancement
