### ISSUE TITLE
ACVM changelogs in release PRs accrue instead of start fresh on new versions

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#4785] opened 2024-04-11 18:28 UTC
### Aim

Reading ACVM changelogs to learn what is new in new versions.

### Expected Behavior

Changelogs should capture new changes in each new version, instead of accumulative changes across versions.

### Bug

ACVM changelogs currently accumulate across versions in release PRs.

For example:
- 0.42.0: https://github.com/noir-lang/noir/pull/4526
- 0.43.0: https://github.com/noir-lang/noir/pull/4632
- Difference: https://www.diffchecker.com/eLBiTPXI/

### Project Impact

Nice-to-have

### Impact Context

Fixing it could make developers' lives checking and working with ACVM changes easier.

### Additional Context

The changelogs aren't formally published anywhere today, so the number of developers this Issue currently affects is likely limited.

Growing interest in integrating different proving backends with ACIR could drive up impact of this Issue.

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment] 2024-04-20 22:13
Duplicate of #3604

**Closed by TomAFrench** 2024-04-20 22:13 UTC
Labels: bug, good first issue, ACIR/ACVM, CI
