### ISSUE TITLE
Point Addition in Unentered else Block Causes Circuit Failure

### ISSUE THREAD

**Issue by LHerskind** [noir-lang/noir#5045] opened 2024-05-17 10:53 UTC
### Aim

A point addition inside an else that is **NOT** "entered" will cause the circuit to fail entirely. The simulator seems to apply the checks when generating the witness and if using 0 as the base value just fails. 

I encountered this when having a computation that is only to happen when we have non-zero values, but anyway fails even if unused. A minimal test to reproduce is here. 

```
#[test]
fn weird_add() {
    let a = EmbeddedCurvePoint {
        x: 0x1d8eb4378a3bde41e0b6a9a8dcbd21b7ff9c51bdd6ca13ce989abbbf90df3666,
        y: 0x06075b63354f2504f9cddba0b94ed0cef35fc88615e69ec1f853b51eb79a24a0
    };

    let aa = a.double();

    if aa.x == a.add(a).x {
        println(f"We are not trying to do a double of zero");
    } else {
        println("We are trying to do a double of zero");
        let d = EmbeddedCurvePoint { x: 0, y: 0 }.double();
        println(f"d*2 {d}");
    }
}
```

Similar failure is possible with the `multi_scalar_mul` and `fixed_base_scalar_mul` if providing fields with values > 128 bits inside the if. 

### Expected Behavior

I expected to see 
```bash
We are not trying to do a double of zero
```
And have the test pass. 

### Bug

Instead the test fails with the following log.

```bash
We are not trying to do a double of zero
[noir_aztec] Testing encrypted_logs::payload::weird_add... FAIL
Failed to solve program: 'Failed to solve blackbox function: embedded_curve_add, reason: Point (0000000000000000000000000000000000000000000000000000000000000000, 0000000000000000000000000000000000000000000000000000000000000000) is not on curve'
```

### To Reproduce

1. Run the test
2. Profit???
3.
4.

### Project Impact

Blocker

### Impact Context

We need to use the computation to constrain log production in Aztec.

### Workaround

None

### Installation Method

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment] 2024-05-17 11:20
This is addressed by https://github.com/AztecProtocol/aztec-packages/pull/6384

Dupe of https://github.com/noir-lang/noir/issues/4978

**Comment by TomAFrench** [comment] 2024-05-17 13:28
Reopening as this is actually different.

**Comment by TomAFrench** [comment] 2024-05-17 14:30
We'll add some behaviour in the flattening pass to apply predicates to these inputs in if statements. This will be blocked pending being able to represent the point at infinity for now though.

**Closed** 2024-05-30 13:47 UTC
Labels: bug
