### ISSUE TITLE
Rightshift `>>` does not work on values where the `rhs` is larger than bit size

### ISSUE THREAD

**Issue by Ethan-000** [noir-lang/noir#2345] opened 2023-08-16 14:56 UTC
### Aim

`nargo execute`
```rust
fn main() {
    let a:u8 = 0;
    let b:u8  = 10; 

    let c = a >> b;
    std::println(c);
}
```

### Expected Behavior

return 0

### Bug

```rust
The application panicked (crashed).
Message:  attempt to divide by zero
Location: /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/num/mod.rs:933
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

Compiled from source

### Nargo Version

nargo 0.10.2 (git version hash: c11c810d343adcf5286445b8863ceb1f19efcb52, is dirty: false)

### Additional Context

this causes https://github.com/shuklaayush/noir-bigint/ test shl1 to panic i think cc @kevaundray 

### Would you like to submit a PR for this Issue?

Maybe

**Comment by TomAFrench** [comment] 2023-08-16 14:58
Looks to be a duplicate of https://github.com/noir-lang/noir/issues/2250

**Closed by TomAFrench** 2023-08-16 14:58 UTC
Labels: bug
