### ISSUE TITLE
Noir program attempts to read uninitialised memory

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2133] opened 2023-08-02 20:01 UTC
Reopening @ax0's issue #2099 based on the new error.

### Aim

Generate a proof for [this program](https://github.com/aragonzkresearch/noir-trie-proofs/tree/main/tests/depth_8_storage_proof).

### Expected Behavior

A proof is successfully generated.

### Bug

We get the following error:
```
$ nargo execute
The application panicked (crashed).
Message:  Should not read uninitialized memory
Location: /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/acvm-0.21.0/src/pwg/memory_op.rs:26

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### To Reproduce

1. `git clone https://github.com/aragonzkresearch/noir-trie-proofs`
2. `cd noir-trie-proofs/tests/depth_8_storage_proof`
3. `nargo execute`

### Installation Method

Compiled from source

### Nargo Version

nargo 0.9.0 (git version hash: a07b8a48924865d8425d35e40c75f48a13a81935, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment] 2023-08-02 20:03
Ah, I hoped this would be fixed by #2106. I can confirm this is still an issue after that has been merged.

**Comment by kevaundray** [comment] 2023-08-16 17:56
@jfecher can you check if this has been solved?

**Comment by jfecher** [comment] 2023-08-16 18:08
@kevaundray a Nargo bug with nested crates is preventing me from testing it. When trying to run the integration test, Nargo complains the parent directory is a lib instead of a bin target even though I'm trying to run the test in a subdirectory which is a bin target.

**Comment by vezenovm** [comment] 2023-08-17 18:09
> When trying to run the integration test, Nargo complains the parent directory is a lib instead of a bin target even though I'm trying to run the test in a subdirectory which is a bin target.

cc'ing @phated as I am not sure if this is the desired functionality or a bug. If it is a bug we can make a separate issue. I also had to move the subdirectory outside of the main `noir-trie-proofs` directory to reproduce this issue.

**Comment by phated** [comment] 2023-08-17 19:47
> as I am not sure if this is the desired functionality or a bug.

It's both. lol. Please open an issue so it can be prioritized.

**Comment by vezenovm** [comment] 2023-08-17 21:05
The panic is a bug, but there is also an error in their program. We are not checking for index out of bounds on dynamic arrays. I'm working on a fix.

I was able to reproduce this on our `array_dynamic` test by adding 20 at the top of main. I am also working with a local version of ACVM that shows me the index we are trying to access in the memory block:
```
    let idx = (z - 5*t - 5) as Field + 20;
    //dynamic array test
    dyn_array(x, idx, idx - 3); 
```
This errors out with:
```
The application panicked (crashed).
Message:  Should not read uninitialized memory at index 24
Location: /mnt/user-data/maxim/acvm/acvm/src/pwg/memory_op.rs:30
```
When working with the project linked in the issue, I was get a panic with an index one greater than the specified array being accessed. Due to this I think the project linked most likely has an index out of bounds bug, just that the compiler needs to have a clear error and not a panic.

**Comment by vezenovm** [comment] 2023-08-18 20:07
After some deeper investigation this looks like it may be a deeper error. I made a fix that checks for loop out of bounds and on the simple case in `array_dynamic` I am getting a failed constraint error instead of a panic as expect. However, I am still getting a panic in the linked project.

**Comment by vezenovm** [comment] 2023-08-21 18:57
PR #2389 has included actual location data to ACIR memory operations. The missing location data is a bug in its own right, but has also exposed another issue with how we are handling call stacks. From the PR description:

The new location data has also exposed the actual bug that occurs in #2133. It looks like we are not handling locations correctly during flattening. A smaller reproduced snippet of the storage proof example is provided in the `dynamic_array_index`. If the dynamic array is accessed with an index out of bounds later after flattening, only the then case of the array merger is shown. For example

```rust
    if z == 20 {
        x[0] = x[4];
    } else {
        x[idx] = 10;
        for i in 0..5 {
            x[idx] = x[i];
        }
    }
    // TODO(#2133): This line should be where we show the error
    // but instead it will show x[0] == x[4] as the line where there is an index out of bounds
    assert(x[idx] != 0)
```
This bug is also seen in the storage proof example, which will return the below output when calling `nargo execute`:
<img width="652" alt="Screenshot 2023-08-21 at 2 53 15 PM" src="https://github.com/noir-lang/noir/assets/43554004/83ed583e-5ddf-4628-89f8-d1d24c5373b8">

However, based on the smaller snippet above, it looks to be using the incorrect location, as the array access being reported as an error is within the then case of an if statement:
```rust
        if ((i + n) as u32) < (N as u32)
        {
            out[i] = input[i+n];
        }
```

**Comment by Savio-Sou** [comment] 2023-08-28 10:48
https://github.com/noir-lang/noir/pull/2389 was a step towards a fix, but not the full fix.

**Comment by vezenovm** [comment] 2023-08-29 01:19
> #2389 was a step towards a fix, but not the full fix.

Thanks, I had not realized this got closed by that PR.

**Comment by ax0** [comment] 2023-08-31 16:42
I'm not sure this has been resolved. I'm still getting an index out of bounds error on commit f71695092dab62ddf3d4f9f4ffc2b99e67428ace.

**Comment by vezenovm** [comment] 2023-08-31 17:06
Ah this should not have been closed, as the change was only incldued in ACVM. More context on the fix can be found here (https://github.com/noir-lang/noir/issues/2493)

**Comment by Savio-Sou** [comment] 2023-09-01 06:32
> as the change was only incldued in ACVM

Is it just a wait for ACVM v0.24.0 that contains the fix to go into Noir?

**Comment by Savio-Sou** [comment] 2023-09-14 07:29
Is this an open issue still?

**Comment by Savio-Sou** [comment] 2023-09-14 08:51
Closed, potentially with https://github.com/noir-lang/noir/pull/2504.

**Closed by Savio-Sou** 2023-09-14 08:51 UTC
Labels: bug, nouns, E-LOW, E-MEDIUM
